x = input('Digite qualquer coisa: ')
print('É do tipo primitivo: ', type(x))
print('Só tem espaços? ', x.isspace())
print('Possui Apenas Números? ', x.isnumeric(), '!')
print('Possui Apenas Letras? ', x.isalpha(), '!')
print('Possui letra ou número? ', x.isalnum())
print('Possui apenas letras maiúsculas? ', x.isupper())
print('Possui apenas letras minúsculas? ', x.islower())
print('Está capitalizada? ', x.istitle())
